#remote_theme: jekyll/minima
remote_theme: jekyll/minima@d4d779a

google_analytics: G-Y20Q9JQGGJ


collections:
  posts:
    output: false

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default

exclude:
  - "_posts"

title: GenAPIre

author:
  name: GenAPIre
  email: genapire@mobulum.com

minima:
  skin: classic
  social_links:
    - title: genAPIre repository at GitHub
      icon: github
      url: "https://github.com/genapire/api"

    - title: Discord server Mobulum/GenAPIre
      icon: discord
      url: "https://discord.gg/rwJcE5Zwez"

