remote_theme: jekyll/minima

collections:
 posts:
  output: false

defaults:
 - scope:
    path: ""
    type: "pages"
   values:
    layout: default

exclude:
 - "_posts"
 - "README.md"

title: Gen(API)re

author:
 name: Gen(API)re
 email: genapire@mobulum.com

minima:
 skin: classic

